export const localBusinessJsonLd = {
  '@context': 'https://schema.org',
  '@type': ['LocalBusiness', 'PhotographyBusiness'],
  name: 'The Flash Room Studio',
  alternateName: 'TFR Studio',
  url: 'https://theflashroom.in',
  logo: {
    '@type': 'ImageObject',
    url: 'https://theflashroom.in/og-image.png',
    width: 1200,
    height: 630,
  },
  image: [
    'https://theflashroom.in/og-image.png',
    'https://theflashroom.in/og-image1.png',
  ],
  description:
    'Award-winning wedding & event photography and videography studio based in Mumbai. Cinematic storytelling for weddings, pre-weddings, maternity, baby showers, and celebrations. Available Pan-India and internationally.',
  telephone: ['+91 91366 98930', '+91 99673 99913'],
  email: 'tfrstudio07@gmail.com',
  address: {
    '@type': 'PostalAddress',
    streetAddress: 'Bhandup',
    addressLocality: 'Mumbai',
    addressRegion: 'Maharashtra',
    postalCode: '400078',
    addressCountry: 'IN',
  },
  geo: {
    '@type': 'GeoCoordinates',
    latitude: 19.1664,
    longitude: 72.9446,
  },
  hasMap:
    'https://www.google.com/maps/search/?api=1&query=The+Flash+Room+Studio+Mumbai',
  areaServed: [
    { '@type': 'City', name: 'Mumbai' },
    { '@type': 'City', name: 'Delhi' },
    { '@type': 'City', name: 'Bangalore' },
    { '@type': 'City', name: 'Jaipur' },
    { '@type': 'City', name: 'Udaipur' },
    { '@type': 'City', name: 'Goa' },
    { '@type': 'City', name: 'Pune' },
    { '@type': 'Country', name: 'India' },
  ],
  priceRange: '₹₹₹',
  currenciesAccepted: 'INR',
  paymentAccepted: 'Cash, Bank Transfer, UPI',
  openingHoursSpecification: [
    {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: [
        'Monday',
        'Tuesday',
        'Wednesday',
        'Thursday',
        'Friday',
        'Saturday',
      ],
      opens: '10:00',
      closes: '19:00',
    },
    {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: 'Sunday',
      opens: '11:00',
      closes: '17:00',
    },
  ],
  sameAs: [
    'https://www.instagram.com/tfrstudio__',
    'https://www.facebook.com',
    'https://www.youtube.com',
  ],
  knowsAbout: [
    'Wedding Photography',
    'Wedding Videography',
    'Pre-Wedding Photography',
    'Event Photography',
    'Maternity Photography',
    'Baby Shower Photography',
    'Birthday Photography',
    'Destination Wedding Photography',
    'Cinematography',
  ],
  serviceType: [
    'Wedding Photography',
    'Wedding Videography',
    'Pre-Wedding Shoots',
    'Event Coverage',
    'Maternity Photography',
    'Baby Shower Photography',
    'Birthday Photography',
  ],
};
